In [ ]:
# Verificar si estamos en Google Colab
try:
    import google.colab
    IN_COLAB = True
    print(" Ejecutándose en Google Colab")
except ImportError:
    IN_COLAB = False
    print(" No está en Google Colab")

# Verificar recursos disponibles en Colab
if IN_COLAB:
    # Verificar GPU disponible
    import tensorflow as tf
    print(" Verificando recursos de hardware:")
    print(f"   - GPUs disponibles: {len(tf.config.list_physical_devices('GPU'))}")

    if len(tf.config.list_physical_devices('GPU')) > 0:
        print("   - Tipo GPU:", tf.config.list_physical_devices('GPU')[0])
        print("    GPU activada - Ideal para Deep Learning")
    else:
        print("     Solo CPU disponible - Suficiente para esta práctica")

    # Verificar RAM disponible
    import psutil
    ram_gb = round(psutil.virtual_memory().total / (1024**3), 1)
    print(f"   - RAM disponible: {ram_gb} GB")
    print(f"   - Almacenamiento temporal: ~100GB")

# Instalar librerías adicionales específicas para Colab
if IN_COLAB:
    print("\n Instalando librerías adicionales en Colab...")
    !pip install -q plotly kaleido  # Para gráficos interactivos
    !pip install -q seaborn --upgrade  # Asegurar última versión
    print(" Instalación completada")



 Ejecutándose en Google Colab
 Verificando recursos de hardware:
   - GPUs disponibles: 0
     Solo CPU disponible - Suficiente para esta práctica
   - RAM disponible: 12.7 GB
   - Almacenamiento temporal: ~100GB

 Instalando librerías adicionales en Colab...
 Instalación completada


In [ ]:
## 1. NumPy: Arrays y Operaciones Básicas

#NumPy es la librería base para el cálculo numérico en Python.
#Permite trabajar con arreglos multidimensionales de manera eficiente.

#En esta sección exploraremos:
#- Creación de arrays
#- Indexación
#- Operaciones matemáticas
#- Transformaciones (reshape)

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

print("Librerías cargadas correctamente.")

### 1.1 Creación de Arrays


#Podemos crear arrays de NumPy a partir de listas, rangos o funciones
#como `arange()` y `linspace()`.

a = np.array([1, 2, 3, 4])
b = np.arange(0, 10, 2)
c = np.linspace(0, 1, 5)

a, b, c

### Ejercicio 1 — Arrays

#Crea un array del 1 al 12, conviértelo en una matriz 3x4 y muestra:

#- La segunda fila
#- La tercera columna
#- El elemento en la posición [2,3]

#Este ejercicio practica indexación y `reshape`.

arr = np.arange(1, 13).reshape(3, 4)

print("Matriz:\n", arr)
print("Segunda fila:", arr[1, :])
print("Tercera columna:", arr[:, 2])
print("Elemento fila 2, col 3:", arr[1, 2])

### 1.2 Operaciones Matemáticas

#NumPy permite realizar operaciones vectorizadas que son más rápidas que las listas tradicionales.
x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])

print("Suma:", x + y)
print("Producto:", x * y)
print("Promedio:", x.mean())
print("Desviación estándar:", x.std())

Librerías cargadas correctamente.
Matriz:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Segunda fila: [5 6 7 8]
Tercera columna: [ 3  7 11]
Elemento fila 2, col 3: 7
Suma: [11 22 33 44]
Producto: [ 10  40  90 160]
Promedio: 25.0
Desviación estándar: 11.180339887498949


In [ ]:
# FUNDAMENTOS DE PANDAS
## 2. Pandas: Manejo de Datos Tabulares


#Pandas permite manipular datos en estructuras tipo tabla,llamadas DataFrames. En esta sección usaremos el dataset **Titanic** de Seaborn para realizar análisis exploratorio.
titanic = sns.load_dataset("titanic")
titanic.head()

### 2.1 Exploración básica del dataset Titanic

#El dataset contiene información sobre:
#- Sexo
#- Clase del pasajero
#- Edad
#- Tarifa
#- Supervivencia

#Revisamos tipos de datos, dimensiones y estadísticas.
titanic.info()
titanic.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


survived      pclass   sex         age       sibsp       parch  \
count   891.000000  891.000000   891  714.000000  891.000000  891.000000   
unique         NaN         NaN     2         NaN         NaN         NaN   
top            NaN         NaN  male         NaN         NaN         NaN   
freq           NaN         NaN   577         NaN         NaN         NaN   
mean      0.383838    2.308642   NaN   29.699118    0.523008    0.381594   
std       0.486592    0.836071   NaN   14.526497    1.102743    0.806057   
min       0.000000    1.000000   NaN    0.420000    0.000000    0.000000   
25%       0.000000    2.000000   NaN   20.125000    0.000000    0.000000   
50%       0.000000    3.000000   NaN   28.000000    0.000000    0.000000   
75%       1.000000    3.000000   NaN   38.000000    1.000000    0.000000   
max       1.000000    3.000000   NaN   80.000000    8.000000    6.000000   

              fare embarked  class  who adult_male deck  embark_town alive  \
count   891.000000      889    891  891        891  203          889   891   
unique         NaN        3      3    3          2    7            3     2   
top            NaN        S  Third  man       True    C  Southampton    no   
freq           NaN      644    491  537        537   59          644   549   
mean     32.204208      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
std      49.693429      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
min       0.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
25%       7.910400      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
50%      14.454200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
75%      31.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
max     512.329200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   

       alone  
count    891  
unique     2  
top     True  
freq     537  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

In [ ]:
###  Ejercicio 2 — Filtrado

#Realiza lo siguiente usando el Titanic dataset:

#1. Filtrar pasajeros mayores de 30 años
#2. Mostrar solo las mujeres de primera clase
#3. Calcular el promedio de edad por sexo

#Este ejercicio refuerza la manipulación básica de DataFrames.
filtro1 = titanic[titanic["age"] > 30]
filtro2 = titanic[(titanic["sex"] == "female") & (titanic["class"] == "First")]
promedios = titanic.groupby("sex")["age"].mean()

filtro1.head(), filtro2.head(), promedios

(    survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
 1          1       1  female  38.0      1      0  71.2833        C  First   
 3          1       1  female  35.0      1      0  53.1000        S  First   
 4          0       3    male  35.0      0      0   8.0500        S  Third   
 6          0       1    male  54.0      0      0  51.8625        S  First   
 11         1       1  female  58.0      0      0  26.5500        S  First   
 
       who  adult_male deck  embark_town alive  alone  
 1   woman       False    C    Cherbourg   yes  False  
 3   woman       False    C  Southampton   yes  False  
 4     man        True  NaN  Southampton    no   True  
 6     man        True    E  Southampton    no   True  
 11  woman       False    C  Southampton   yes   True  ,
     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
 1          1       1  female  38.0      1      0   71.2833        C  First   
 3          1       1  female  35.0

In [ ]:
### 2.2 Manejo de valores faltantes

#Pandas permite:
#- Identificar valores nulos
#- Reemplazarlos
#- Eliminarlos

#Revisamos los valores faltantes del dataset Titanic.
titanic.isnull().sum()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True